name = "BootstrapVirasoro"
uuid = "ca6c609c-7c6b-4ea6-be06-ee6e3ced7d6c"
authors = ["Paul_Roux"]
version = "0.0.0-DEV"

[deps]
ArbNumerics = "7e558dbc-694d-5a72-987c-6f4ebed21442"
BarnesDoubleGamma = "8c4ec0a7-3a81-41b6-9d5f-01f75984e8d3"
EllipticFunctions = "6a4e32cb-b31a-4929-85af-fb29d9a80738"
Memoization = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
ArbNumerics = "1"
BarnesDoubleGamma = "1"
EllipticFunctions = "2"
Memoization = "0"
SpecialFunctions = "2"
julia = "1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
