name = "BootstrapVirasoro"
uuid = "ca6c609c-7c6b-4ea6-be06-ee6e3ced7d6c"
authors = ["Paul_Roux"]
version = "0.0.0-DEV"

[deps]
BarnesDoubleGamma = "8c4ec0a7-3a81-41b6-9d5f-01f75984e8d3"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
EllipticFunctions = "6a4e32cb-b31a-4929-85af-fb29d9a80738"
Memoization = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"
MutableArithmetics = "d8a4904e-b15c-11e9-3269-09a3773c0cb0"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
BarnesDoubleGamma = "1"
Distributed = "1"
EllipticFunctions = "2"
Memoization = "0"
MutableArithmetics = "1"
SpecialFunctions = "2"
julia = "1"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[targets]
test = ["BenchmarkTools"]
