name = "JuliVirBootstrap"
uuid = "ca6c609c-7c6b-4ea6-be06-ee6e3ced7d6c"
authors = ["Paul_Roux"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
